# Environment Variables

export LANG=$DEVENV_LOCALE;
export SSH_KEY_PATH=/home/$DEVENV_USER/.ssh/id_rsa;
export NVIM_LISTEN_ADDRESS="/home/$DEVENV_USER/nvimsocket"
export EDITOR="nvr --nostart --remote-wait-silent "
export VISUAL="$EDITOR"
export PAGER="nvr --nostart --remote-silent - "
export IDE="nvr --nostart --remote-tab-silent "

# eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)

source /home/$DEVENV_USER/dotfiles/zshrc

